feat: support coroutine functions
pyapp-kit/psygnal pull request #346
Opened 2024-12-20 02:56 UTC by tlambert03

2024-12-20 08:04 UTC, davidbrochart commented
Thanks for the quick PR @tlambert03!
In #345 you mentioned that:
> psygnal itself has no concept of an event loop (it's a "bring-your-own-event-loop" library)

But this PR currently assumes that the event loop is asyncio. However Trio and AnyIO are very popular, so I'm wondering how we could support them and really be event-loop agnostic.

2024-12-20 08:46 UTC, davidbrochart commented
Because structured concurrency always needs a task group in order to launch tasks, I think it's better to not support async callbacks in psygnal. One can just use a sync callback, and have the async logic in the user code where the new value is put synchronously in a stream, and a background task gets the values from the stream asynchronously. That way the user can launch this background task in the appropriate task group.

2024-12-20 20:25 UTC, tlambert03 commented
Thanks for your input!

> I think it's better to not support async callbacks in psygnal. One can just use a sync callback, and have the async logic in the user code where the new value is put synchronously in a stream, and a background task gets the values from the stream asynchronously.

Are you sure?  I'm definitely happy to do whatever we can here to make using coroutines in psygnal easier.  That could include supporting auto detection of asyncio, trio, or anyio.

I don't have a ton of personal experience with async/await, so would happily take advice and implement whatever folks suggest.
At the very least we could add some better documentation explaining/showing the strategy you mentioned for using a sync function to put a task in a stream.

And if there are conveniences we could add around that pattern, that's fine too

2025-02-17 15:30 UTC, davidbrochart commented on tests/test_coroutines.py
> +    await asyncio.sleep(0)
```suggestion
    while True:
        if backend.running:
            break
        await asyncio.sleep(0)
```

2025-02-17 15:31 UTC, tlambert03 commented on tests/test_coroutines.py
> +    await asyncio.sleep(0)
thanks.... yes, I'm going to have a number of best-practice questions for you :) i really don't use this stuff much.  just a moment and I will post more questions

2025-02-17 15:43 UTC, tlambert03 commented on src/psygnal/_weak_callback.py
> +        cast("_AsyncBackend", get_async_backend())._put((self, args))
@davidbrochart one change I had to make here was to put the WeakCallback itself in the queue, rather than the dereferenced object, in order to avoid holding strong references.  (minor detail... but something this library tries hard to avoid for reasons of having been bitten by it in the past).  See corresponding change in `_AsyncBackend.call_back`

2025-02-17 15:43 UTC, tlambert03 commented on tests/test_coroutines.py
> +    backend = _async.set_async_backend("asyncio")
@davidbrochart I think one of the biggest questions for me is "proper usage".  This is what I did to get the tests to work (so far, just for asyncio).  But note that I had to allow `_async.set_async_backend("asyncio")` to be called *multiple* times within a session... (with the restriction that it be called with the same backend).

An important thing to note there though is that, in `set_async_backend`, I actually had to let it re-initialize the backend (can't just return the already instantiated backend)... otherwise I get 

```
    def _check_closed(self):
        if self._closed:
>           raise RuntimeError('Event loop is closed')
E           RuntimeError: Event loop is closed
```

on follow-up tests.


Another question I have here is how to test all three backends.  Is it possible within a single python session?

2025-02-17 15:44 UTC, tlambert03 commented on tests/test_coroutines.py
> +    await asyncio.sleep(0.01)
similar to your comment above... i suspect this is flaky.  Should we have an API to wait until the backend has no items in the queue?

2025-02-17 15:52 UTC, tlambert03 commented
one additional note, I'm skipping the `_async.py` module from the mypyc compilation targets for now.  When I include it, it's giving me odd, seemingly-unrelated errors in other modules.  it *might* have to do with trio/anyio missing from the environment during mypyc compilation.  But I think it's probably just asking for problems anyway.   The key bits (signal emissions and weak-callbacks) are still compiled

2025-02-17 15:55 UTC, davidbrochart commented on src/psygnal/_weak_callback.py
> +        cast("_AsyncBackend", get_async_backend())._put((self, args))
I think this is fine :+1:

2025-02-17 16:20 UTC, davidbrochart commented on tests/test_coroutines.py
> +    backend = _async.set_async_backend("asyncio")
Maybe we should still prevent `set_async_backend()` from being called multiple times, unless a `clear_async_backend()` function is called in between (mostly for tests)?

2025-02-17 16:20 UTC, davidbrochart commented on tests/test_coroutines.py
> +    await asyncio.sleep(0.01)
That's a possibility, but a simpler approach could be to set an event in the mock, and wait for it (with a timeout)?

2025-06-29 15:43 UTC, tlambert03 commented
Hey @davidbrochart,  sorry again for the delay on this.  I cleaned it up a bit and added tests for all three backends.  I'm sure the details are all a little fuzzy for you at this point; but I wrote up some user-facing documentation that describes how we expect people to use this new feature:

https://psygnal--346.org.readthedocs.build/en/346/guides/async/

It would be great if you could just take a quick look at that page, to make sure it's accurate and consistent with how you envisioned this feature being used, and feel free to suggest changes on wording.   If the basic API pattern is correct, we can merge and I'll get this in the next upcoming release

2025-06-30 09:38 UTC, davidbrochart requested changes
Thanks @tlambert03, that looks good.
I'd just like the `running` property of a backend to be an event, so that it can just be awaited.

2025-06-30 09:38 UTC, davidbrochart commented on docs/guides/async.md
> +            await asyncio.sleep(0.01)
I would expect waiting for an event:
```suggestion
        await backend.running.wait()  # (2)!
```

2025-06-30 09:38 UTC, davidbrochart commented on docs/guides/async.md
> +    2.  Wait for the backend to task be ready before connecting the signal.
```suggestion
    2.  Wait for the backend to be ready before connecting the signal.
```

2025-06-30 09:38 UTC, davidbrochart commented on docs/guides/async.md
> +                await anyio.sleep(0.01)
```suggestion
            await backend.running.wait()  # (3)!
```

2025-06-30 09:38 UTC, davidbrochart commented on docs/guides/async.md
> +                await trio.sleep(0.01)
```suggestion
            await backend.running.wait()  # (3)!
```

2025-06-30 09:38 UTC, davidbrochart commented on src/psygnal/_async.py
> +        self._running = False
```suggestion
```

2025-06-30 09:38 UTC, davidbrochart commented on src/psygnal/_async.py
> +        self._loop = asyncio.get_running_loop()
```suggestion
        self._loop = asyncio.get_running_loop()
        self._running = asyncio.Event()
```

2025-06-30 09:38 UTC, davidbrochart commented on src/psygnal/_async.py
> +        if self.running:
```suggestion
        if self.running.is_set():
```

2025-06-30 09:38 UTC, davidbrochart commented on src/psygnal/_async.py
> +        self._running = True
```suggestion
        self._running.set()
```

2025-06-30 09:38 UTC, davidbrochart commented on src/psygnal/_async.py
> +            self._running = False
```suggestion
            self._running.clear()
```

2025-06-30 09:38 UTC, davidbrochart commented on src/psygnal/_async.py
> +        )
```suggestion
        )
        self._running = anyio.Event()
```

2025-06-30 09:38 UTC, davidbrochart commented on src/psygnal/_async.py
> +        if self.running:
```suggestion
        if self.running.is_set():
```

2025-06-30 09:38 UTC, davidbrochart commented on src/psygnal/_async.py
> +        self._running = True
```suggestion
        self._running.set()
```

2025-06-30 09:38 UTC, davidbrochart commented on src/psygnal/_async.py
> +            self._running = False
```suggestion
            self._running = anyio.Event()
```

2025-06-30 09:38 UTC, davidbrochart commented on src/psygnal/_async.py
> +        )
```suggestion
        )
        self._running = trio.Event()
```

2025-06-30 09:38 UTC, davidbrochart commented on src/psygnal/_async.py
> +        if self.running:
```suggestion
        if self.running.is_set():
```

2025-06-30 09:38 UTC, davidbrochart commented on src/psygnal/_async.py
> +        self._running = True
```suggestion
        self._running.set()
```

2025-06-30 09:38 UTC, davidbrochart commented on src/psygnal/_async.py
> +            self._running = False
```suggestion
            self._running = trio.Event()
```

2025-06-30 09:38 UTC, davidbrochart commented on src/psygnal/_weak_callback.py
> +        if not backend.running:
```suggestion
        if not backend.running.is_set():
```

2025-06-30 09:38 UTC, davidbrochart commented on tests/test_coroutines.py
> +        while not backend.running:
```suggestion
        while not backend.running.is_set():
```

2025-06-30 09:38 UTC, davidbrochart commented on tests/test_coroutines.py
> +    while not backend.running:
```suggestion
    while not backend.running.is_set():
```

2025-06-30 09:38 UTC, davidbrochart commented on tests/test_coroutines.py
> +    assert backend.running
```suggestion
    assert backend.running.is_set()
```

2025-06-30 09:38 UTC, davidbrochart commented on tests/test_coroutines.py
> +                        await trio.sleep(0)
```suggestion
                    await backend.running.wait()
```

2025-06-30 09:38 UTC, davidbrochart commented on tests/test_coroutines.py
> +                        await anyio.sleep(0)
```suggestion
                    await backend.running.wait()
```

2025-06-30 09:38 UTC, davidbrochart commented on tests/test_coroutines.py
> +                    await asyncio.sleep(0)
```suggestion
                await backend.running.wait()
```

2025-06-30 09:38 UTC, davidbrochart commented on tests/test_coroutines.py
> +                        await trio.sleep(0)
```suggestion
                    await backend.running.wait()
```

2025-06-30 09:38 UTC, davidbrochart commented on tests/test_coroutines.py
> +                    await anyio.sleep(0)
```suggestion
                await backend.running.wait()
```

2025-07-01 13:15 UTC, tlambert03 commented
thanks @davidbrochart!

2025-07-01 13:42 UTC, davidbrochart commented
Oh, then internal Trio errors on Windows don't look good.

2025-07-01 13:49 UTC, tlambert03 commented
> Oh, then internal Trio errors on Windows don't look good.

Was just looking into that.  I actually think it's just a side effect of me greedily trying to test all three backends in the same runtime process.  I think https://github.com/pyapp-kit/psygnal/pull/346/commits/982e4aad2c266453b59e2d5c844fdbc701975ddf may have fixed it

2025-07-01 15:01 UTC, tlambert03 commented
the failing benchmarks are these:

```
| Change   | Before [8bf2d823] <main>   | After [c8af7ac1]    |   Ratio | Benchmark (Parameter)                         |
|----------|----------------------------|---------------------|---------|-----------------------------------------------|
| +        | 1.77±0.01μs                | 2.90±0.01μs         |    1.64 | benchmarks.ConnectSuite.time_connect_nochecks |
| +        | 19.8±0.1μs                 | 23.1±0.9μs          |    1.16 | benchmarks.ConnectSuite.time_connect_method   |
```

they are slight enough, and in things that don't get called frequently enough (unlike like emit), and already around a microseconds, that I'm not worried about them

2025-07-01 15:01 UTC, merged